#!/usr/bin/env bash
# Update package repository and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx


echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/custom_404
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF'


sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/
sudo nginx -t
sudo systemctl reload nginx
