#!/usr/bin/env bash
# If config file is not linked correctly, configures nginx to listen on port 80 

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
